language: python
python:
  - "3.6"
  - "3.8"

# command to install dependencies
install:
  - pip install -qq flake8
  - pip install .
  - pip install -r requirements-test.txt

# command to run tests
script:
  - flake8 --version
  - flake8 trading_ig
#  - nosetests  # should be fixed https://github.com/ig-python/ig-markets-api-python-library/issues/35
