
name: trading_ig integration test

on:
  #schedule:
  #  - cron: '0 1 * * *'
  workflow_dispatch:
    
jobs:
  build:

    runs-on: ubuntu-20.04

    steps:

    - uses: actions/checkout@v2

    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install Poetry
      uses: abatilo/actions-poetry@v2.1.4
      with:
        poetry-version: 1.1.12

    - name: Install dependencies
      run: |
        python -m poetry install --extras "pandas munch tenacity"

    - name: Integration test with pytest
      env:
        IG_SERVICE_USERNAME:  ${{ secrets.IG_SERVICE_USERNAME }}
        IG_SERVICE_PASSWORD:  ${{ secrets.IG_SERVICE_PASSWORD }}
        IG_SERVICE_API_KEY:  ${{ secrets.IG_SERVICE_API_KEY }}
        IG_SERVICE_ACC_TYPE:  ${{ secrets.IG_SERVICE_ACC_TYPE }}
        IG_SERVICE_ACC_NUMBER:  ${{ secrets.IG_SERVICE_ACC_NUMBER_1 }}
      run: |
        poetry run coverage run -m --source=trading_ig pytest --log-cli-level=DEBUG --log-format="%(asctime)s %(levelname)s %(message)s" --log-date-format="%Y-%m-%d %H:%M:%S"
        poetry run coverage report

    - name: Coveralls
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        poetry run coveralls --service=github
