name: trading_ig unit tests

on:
  push:

  pull_request:

  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-20.04
    strategy:
      matrix:
        python-version: [ 3.7, 3.8, 3.9 ]

    steps:

    - uses: actions/checkout@v2

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install Poetry
      uses: abatilo/actions-poetry@v2.1.4
      with:
        poetry-version: 1.1.12

    - name: Install dependencies
      run: |
        python -m poetry install --extras "pandas munch tenacity"

    - name: Lint with flake8
      run: |
        python -m poetry run flake8 trading_ig

    - name: Unit tests with pytest
      run: |
        python -m poetry run python -m pytest --ignore=tests/test_integration.py